package br.com.futmatch.infrastructure.adapters.in.web.dto;

public enum ErrorCode {

    PARTIDA_NOT_FOUND,
    USUARIO_NOT_FOUND,
    EMAIL_JA_CADASTRADO,
    CREDENCIAIS_INVALIDAS,
    EMAIL_INVALIDO,
    SENHA_FRACA,
    REQUISICAO_INVALIDA,
    ESTADO_INVALIDO,
    VALIDACAO_FALHOU,
    CORPO_INVALIDO,
    PARAMETRO_INVALIDO,
    PARAMETRO_OBRIGATORIO,
    METODO_NAO_PERMITIDO,
    RECURSO_NAO_ENCONTRADO,
    VIOLACAO_INTEGRIDADE,
    ERRO_INTERNO,
    ACESSO_NAO_AUTORIZADO,
    ACESSO_NEGADO,
    TOKEN_INVALIDO_OU_AUSENTE,
    TOKEN_INVALIDO_OU_ERRO_AUTENTICACAO,
    USUARIO_NAO_ENCONTRADO_OU_NAO_AUTORIZADO,
    RATE_LIMIT_EXCEDIDO
}
